/**
 * @file countries.data.ts
 * @description Single source of truth for international country directories, major cities, and timezones.
 */

import { CountryListing } from '../types/academy.types';

export const COUNTRY_DIRECTORY: CountryListing[] = [
  {
    id: 'uae',
    flag: '🇦🇪',
    country: 'United Arab Emirates (UAE)',
    headline: 'Learn Quran Online in UAE',
    cities: 'Dubai • Sharjah • Abu Dhabi • Ajman • Al Ain • RAK',
    timing: 'Gulf Standard Time (GST / GMT+4) Friendly Slots',
    details: '6 years of esteemed home tuition experience across Sharjah, Dubai & Ajman. Perfectly synchronized with UAE school and office routines.',
    tag: '6 Yrs UAE Experience',
    defaultTimezone: 'Gulf Standard Time (GST / GMT+4)',
  },
  {
    id: 'saudi-arabia',
    flag: '🇸🇦',
    country: 'Saudi Arabia (KSA)',
    headline: 'Learn Quran Online in Saudi Arabia',
    cities: 'Riyadh • Jeddah • Makkah • Madinah • Dammam • Khobar',
    timing: 'Arabia Standard Time (AST / GMT+3) Convenient Slots',
    details: 'Tailored classes for Pakistani and international expatriate families residing in the Kingdom. Flexible after-Asr and after-Isha timings.',
    tag: 'KSA Expat Friendly',
    defaultTimezone: 'Arabia Standard Time (AST / GMT+3)',
  },
  {
    id: 'qatar',
    flag: '🇶🇦',
    country: 'Qatar',
    headline: 'Learn Quran Online in Qatar',
    cities: 'Doha • Al Rayyan • Al Wakrah • Al Khor • Lusail',
    timing: 'Arabian Gulf Time Slots (Morning, Evening & Weekends)',
    details: 'Individualized 1-on-1 Zoom sessions arranged around school and evening family schedules for children and working adults in Qatar.',
    tag: 'Doha & All Cities',
    defaultTimezone: 'Arabia Standard Time (AST / GMT+3)',
  },
  {
    id: 'oman',
    flag: '🇴🇲',
    country: 'Oman',
    headline: 'Learn Quran Online in Oman',
    cities: 'Muscat • Salalah • Sohar • Nizwa • Seeb',
    timing: 'Gulf Time Zone Aligned Schedules (GST / GMT+4)',
    details: 'Structured Noorani Qaida, Nazra, and Hifz programs for families living in Oman seeking experienced Pakistani Quran teachers.',
    tag: 'Muscat & Oman',
    defaultTimezone: 'Gulf Standard Time (GST / GMT+4)',
  },
  {
    id: 'uk',
    flag: '🇬🇧',
    country: 'United Kingdom (UK)',
    headline: 'Learn Quran Online in UK',
    cities: 'London • Birmingham • Manchester • Leeds • Bradford • Glasgow',
    timing: 'GMT / BST After-School (4:00 PM – 9:00 PM) & Weekend Slots',
    details: 'Bilingual (English & Urdu) instruction tailored for British-Muslim youth and adults, ensuring smooth pronunciation and deep Quranic understanding.',
    tag: 'UK After-School Slots',
    defaultTimezone: 'Greenwich Mean Time (GMT / BST)',
  },
  {
    id: 'pakistan',
    flag: '🇵🇰',
    country: 'Pakistan',
    headline: 'Online Quran Classes in Pakistan',
    cities: 'Muzaffargarh • Multan • Lahore • Karachi • Islamabad • Rawalpindi',
    timing: 'Pakistan Standard Time (PKT / GMT+5) All-Day Slots',
    details: 'Direct instruction rooted in 11+ years of madrasa and private tuition leadership in South Punjab and across Pakistan.',
    tag: 'Academy Headquarter',
    defaultTimezone: 'Pakistan Standard Time (PKT / GMT+5)',
  },
  {
    id: 'usa',
    flag: '🇺🇸',
    country: 'United States (USA)',
    headline: 'Learn Quran Online in USA',
    cities: 'New York • Texas • California • Chicago • Florida',
    timing: 'EST, CST, MST, PST Flexible Classes',
    details: 'Convenient time slots adapted to North American time zones.',
    tag: 'USA Batches',
    defaultTimezone: 'Eastern / Central / Pacific (EST/CST/PST)',
  },
  {
    id: 'canada',
    flag: '🇨🇦',
    country: 'Canada',
    headline: 'Learn Quran Online in Canada',
    cities: 'Toronto • Vancouver • Calgary • Montreal • Ottawa',
    timing: 'EST / PST Convenient Slots',
    details: 'Tailored classes for Canadian-Muslim families.',
    tag: 'Canada Batches',
    defaultTimezone: 'Eastern Standard Time (EST)',
  },
  {
    id: 'australia',
    flag: '🇦🇺',
    country: 'Australia',
    headline: 'Learn Quran Online in Australia',
    cities: 'Sydney • Melbourne • Perth • Brisbane • Adelaide',
    timing: 'AEST & AWST Time Zone Adaptability',
    details: 'Reliable classes connecting Australian-Muslim families.',
    tag: 'Australia Network',
    defaultTimezone: 'Australian Eastern Standard Time (AEST)',
  },
  {
    id: 'kuwait',
    flag: '🇰🇼',
    country: 'Kuwait',
    headline: 'Learn Quran Online in Kuwait',
    cities: 'Kuwait City • Hawalli • Salmiya • Ahmadi',
    timing: 'AST (GMT+3) Convenient Slots',
    details: '1-on-1 Zoom classes for families in Kuwait.',
    tag: 'Kuwait City',
    defaultTimezone: 'Arabia Standard Time (AST / GMT+3)',
  },
  {
    id: 'bahrain',
    flag: '🇧🇭',
    country: 'Bahrain',
    headline: 'Learn Quran Online in Bahrain',
    cities: 'Manama • Riffa • Muharraq',
    timing: 'AST (GMT+3) Slots',
    details: '1-on-1 Zoom classes for families in Bahrain.',
    tag: 'Bahrain',
    defaultTimezone: 'Arabia Standard Time (AST / GMT+3)',
  },
  {
    id: 'germany',
    flag: '🇩🇪',
    country: 'Germany',
    headline: 'Learn Quran Online in Germany',
    cities: 'Berlin • Frankfurt • Munich • Hamburg • Cologne',
    timing: 'CET / CEST Friendly Slots',
    details: 'Tailored for German-Muslim youth and adults.',
    tag: 'Germany',
    defaultTimezone: 'Central European Time (CET)',
  },
  {
    id: 'france',
    flag: '🇫🇷',
    country: 'France',
    headline: 'Learn Quran Online in France',
    cities: 'Paris • Marseille • Lyon • Toulouse',
    timing: 'CET Friendly Slots',
    details: '1-on-1 Zoom classes for families in France.',
    tag: 'France',
    defaultTimezone: 'Central European Time (CET)',
  },
  {
    id: 'italy',
    flag: '🇮🇹',
    country: 'Italy',
    headline: 'Learn Quran Online in Italy',
    cities: 'Rome • Milan • Naples • Turin',
    timing: 'CET Friendly Slots',
    details: 'Classes for Pakistani and Muslim families in Italy.',
    tag: 'Italy',
    defaultTimezone: 'Central European Time (CET)',
  },
  {
    id: 'spain',
    flag: '🇪🇸',
    country: 'Spain',
    headline: 'Learn Quran Online in Spain',
    cities: 'Madrid • Barcelona • Valencia • Seville',
    timing: 'CET Friendly Slots',
    details: 'Classes for families residing in Spain.',
    tag: 'Spain',
    defaultTimezone: 'Central European Time (CET)',
  },
  {
    id: 'new-zealand',
    flag: '🇳🇿',
    country: 'New Zealand',
    headline: 'Learn Quran Online in New Zealand',
    cities: 'Auckland • Wellington • Christchurch',
    timing: 'NZST Friendly Slots',
    details: 'Interactive classes for New Zealand families.',
    tag: 'New Zealand',
    defaultTimezone: 'New Zealand Standard Time (NZST)',
  },
  {
    id: 'malaysia',
    flag: '🇲🇾',
    country: 'Malaysia',
    headline: 'Learn Quran Online in Malaysia',
    cities: 'Kuala Lumpur • Penang • Johor Bahru',
    timing: 'MYT (GMT+8) Slots',
    details: 'Quran classes for expat families in Malaysia.',
    tag: 'Malaysia',
    defaultTimezone: 'Malaysia Time (MYT)',
  },
  {
    id: 'ireland',
    flag: '🇮🇪',
    country: 'Ireland',
    headline: 'Learn Quran Online in Ireland',
    cities: 'Dublin • Cork • Galway • Limerick',
    timing: 'GMT / IST After-School Slots',
    details: 'Bilingual Quran tutoring for families in Ireland.',
    tag: 'Ireland',
    defaultTimezone: 'Greenwich Mean Time (GMT / IST)',
  },
  {
    id: 'norway-sweden',
    flag: '🇳🇴',
    country: 'Norway & Sweden',
    headline: 'Learn Quran Online in Scandinavia',
    cities: 'Oslo • Stockholm • Gothenburg • Bergen',
    timing: 'CET Friendly Slots',
    details: 'Personalized classes for Scandinavian Muslim families.',
    tag: 'Scandinavia',
    defaultTimezone: 'Central European Time (CET)',
  },
  {
    id: 'worldwide',
    flag: '🌍',
    country: 'Other Worldwide Countries',
    headline: 'Worldwide Live Online Quran Classes',
    cities: 'Connecting Students Globally via Zoom HD',
    timing: '24/7 Global Time Zone Flexibility',
    details: 'Welcoming students from any country worldwide.',
    tag: 'Global Access',
    defaultTimezone: 'Universal Time (UTC)',
  },
];
