/**
 * @file courses.data.ts
 * @description Single source of truth for all Core Quran Courses and Specialized Learning Tracks.
 */

import { Course, SpecialProgram } from '../types/academy.types';

export const CORE_COURSES: Course[] = [
  {
    id: 'noorani',
    title: 'Noorani Qaida',
    subtitle: 'Foundational Arabic & Makharij',
    desc: 'Build a strong foundation in Arabic letters, joining compounds, pronunciation, Makharij, and introductory Quran reading.',
    tag: 'Ages 4+ & Beginners',
    arabic: 'القاعدة النورانية',
    badge: 'Ages 4+ & Beginners',
    eyebrow: 'Beginner Level • Ages 4+ & Adults',
    icon: '۞',
    image: '/images/courses/noorani_qaida_v2.jpg',
    action: 'Start Qaida',
    points: [
      'Arabic alphabet recognition & correct sounds',
      'Word joining, Tanween & Harakaat rules',
      'Patient, gentle pacing for kids & beginners',
    ],
    syllabus: [
      'Single & compound Arabic letter recognition (Mufradat & Murakkabat)',
      'Accurate articulation points from throat and mouth (Makharij al-Huroof)',
      'Short and long vowels (Harakaat, Huroof Maddah & Leen)',
      'Tanween, Jazm (Sukoon), and Tashdeed (Shaddah) rules',
      'Word formation and smooth reading without hesitation or stuttering',
      'Basic Tajweed rules applied right from the very first lesson',
    ],
    info: {
      audience: 'Children (Ages 4+) & Adult Beginners',
      duration: '2 to 4 Months (Personalized Pace)',
      format: '1-on-1 Live Zoom HD Video/Audio',
      prerequisites: 'Zero Arabic background needed',
    },
  },
  {
    id: 'nazra',
    title: 'Nazra Quran',
    subtitle: 'Fluent 30 Paras Recitation',
    desc: 'Improve fluency, pronunciation and confidence while reading the complete 30 Paras (Juz) of the Holy Quran with Tajweed.',
    tag: 'All Ages',
    arabic: 'قراءة القرآن الكريم بالترتيل',
    badge: 'Kids, Adults & Families',
    eyebrow: 'Reading Fluency • Complete 30 Paras',
    icon: 'ﷲ',
    image: '/images/courses/nazra_quran_v2.jpg',
    action: 'Start Nazra Quran',
    points: [
      'Recitation of all 30 Paras (Juz) with Tajweed',
      'Real-time error correction & proper Waqf signs',
      'Daily Sabaq rhythm & melodic reading stamina',
    ],
    syllabus: [
      'Recitation of all 30 Paras (Juz) from Surah Al-Fatihah to Surah An-Nas',
      'Continuous Tajweed correction while reading in real-time',
      'Mastery of Quranic stop signs (Waqf Mutlaq, Jaiz, Lazim, Mamnoo)',
      'Building recitation stamina, melodic rhythm, and proper breath control',
      'Daily revision and milestone evaluation after every completed Para',
    ],
    info: {
      audience: 'Students who completed Qaida',
      duration: '6 to 12 Months',
      format: '1-on-1 Live Zoom Interactive Classes',
      prerequisites: 'Completion of Noorani Qaida',
    },
  },
  {
    id: 'hifz',
    title: 'Hifz-ul-Quran',
    subtitle: 'Structured Retention Track',
    desc: 'A structured memorization journey with daily lessons (Sabaq), short-term revision (Sabaqi), consistency, and individual guidance.',
    tag: 'Dedicated Track',
    arabic: 'حفظ القرآن الكريم وتثبيته',
    badge: 'Dedicated Memorization',
    eyebrow: 'Spiritual Preservation • Full or Partial',
    icon: 'ح',
    image: '/images/courses/hifz_quran_v2.jpg',
    action: 'Start Hifz Track',
    points: [
      'Daily new Sabaq & systematic Sabaqi revision',
      'Cumulative Manzil retention cycles (Dhor)',
      '1-on-1 private mentoring by Hafiz scholar',
    ],
    syllabus: [
      'Daily new memorization targets assigned by the teacher (Sabaq)',
      'Sub-recent quarter / Juz revision to lock short-term memory (Sabaqi)',
      'Full cumulative revision cycles to maintain complete retention (Manzil / Dhor)',
      'Mutashabihat (similar verses across different Surahs) mastery',
      'Annual completion and rigorous retention evaluations',
    ],
    info: {
      audience: 'Dedicated Children, Teens & Adults',
      duration: '2 to 4 Years (Full or Selected Surahs)',
      format: '1-on-1 Daily Live Sessions',
      prerequisites: 'Fluent Nazra reading with Tajweed',
    },
  },
  {
    id: 'tajweed',
    title: 'Tajweed Mastery',
    subtitle: 'Vocal Tarteel & Precision Rules',
    desc: 'Learn Makharij, Sifaat, and classical Tajweed rules to recite the Holy Quran correctly, eloquently, and beautifully.',
    tag: 'Intermediate & Advanced',
    arabic: 'أحكام التجويد ومخارج الحروف',
    badge: 'Tajweed Certification',
    eyebrow: 'Theoretical & Practical Certification',
    icon: 'ت',
    image: '/images/courses/tajweed_mastery_v2.jpg',
    action: 'Master Tajweed',
    points: [
      'In-depth Makharij & Sifaat rules mastery',
      'Noon/Meem Saakin, Madd & Qalqalah rules',
      'Classical melodious recitation style',
    ],
    syllabus: [
      'Detailed study of Makharij and Sifaat Lazimah / Aaridah',
      'Rules of Noon Saakin & Tanween (Izhar, Idgham, Iqlab, Ikhfa)',
      'Rules of Meem Saakin (Idgham Shafawi, Ikhfa Shafawi, Izhar Shafawi)',
      'Types of Madd (Natural, Connected, Separated, Compulsory, Lazim)',
      'Ghunnah, Qalqalah, Tafkheem, and Tarqeeq of letters (Raa & Laam)',
      'Classical recitation style of Hafs an Asim',
    ],
    info: {
      audience: 'All levels seeking recitation excellence',
      duration: '3 to 6 Months',
      format: '1-on-1 Live Zoom with audio breakdown',
      prerequisites: 'Basic Arabic reading ability',
    },
  },
  {
    id: 'tarjuma',
    title: 'Quran Translation',
    subtitle: 'Word-by-Word Meaning & Reflection',
    desc: 'Explore the meanings of Quranic verses, understand what you recite in daily Salah, and develop deeper spiritual reflection.',
    tag: 'Teens & Adults',
    arabic: 'ترجمة معاني القرآن الكريم',
    badge: 'Teens & Adults',
    eyebrow: 'Understanding Meaning • Urdu & English',
    icon: 'م',
    image: '/images/courses/quran_translation_v2.jpg',
    action: 'Learn Translation',
    points: [
      'Word-by-word Quranic vocabulary building',
      'Contextual translation of daily Salah & Surahs',
      'Connecting Arabic grammar with life lessons',
    ],
    syllabus: [
      'Word-by-word Quranic vocabulary building',
      'Contextual translation of everyday Surahs and daily Salah prayers',
      'Connecting Arabic grammar roots with translated meanings',
      'Understanding thematic messages and divine directives across Surahs',
    ],
    info: {
      audience: 'Teens, Adults & New Muslims',
      duration: 'Modular (Surah-by-Surah or Full)',
      format: '1-on-1 Live Zoom interactive discussion',
      prerequisites: 'Basic Nazra reading ability',
    },
  },
  {
    id: 'tafseer',
    title: 'Tafseer-ul-Quran',
    subtitle: 'Context & Shan-e-Nuzool',
    desc: 'Study the context, reasons for revelation (Shan-e-Nuzool), legal morals, and practical life lessons of selected Quranic verses.',
    tag: 'In-Depth Study',
    arabic: 'التفسير والتدبر',
    badge: 'Deep Contemplation',
    eyebrow: 'Deep Contemplation & Moral Wisdom',
    icon: 'ع',
    image: '/images/courses/tafseer_quran_v2.jpg',
    action: 'Explore Tafseer',
    points: [
      'Historical context & Asbab an-Nuzool reasons',
      'Stories of Prophets & moral life guidance',
      'In-depth study of Juz Amma & major Surahs',
    ],
    syllabus: [
      'Historical context & Asbab an-Nuzool (Reasons of Revelation)',
      'Stories of Prophets and past nations in the Holy Quran',
      'In-depth study of Juz Amma & major Surahs (Al-Baqarah, Yasin, Al-Mulk, Al-Kahf)',
      'Applying Quranic principles and ethics to modern everyday life',
    ],
    info: {
      audience: 'Teens & Adults seeking spiritual depth',
      duration: 'Ongoing Weekly Lessons',
      format: '1-on-1 Live Zoom study sessions',
      prerequisites: 'Basic understanding of Quran',
    },
  },
  {
    id: 'duas',
    title: 'Masnoon Duas',
    subtitle: 'Daily Sunnah Supplications',
    desc: 'Learn essential daily duas, morning & evening Adhkar, and practical Islamic supplications with proper pronunciation.',
    tag: 'Daily Lifestyle',
    arabic: 'الأدعية المأثورة والأذكار',
    badge: 'Kids & Families',
    eyebrow: 'Daily Lifestyle • Memory & Meaning',
    icon: 'د',
    image: '/images/courses/masnoon_duas_v2.jpg',
    action: 'Learn Duas',
    points: [
      'Daily morning & evening Adhkar (Athkar)',
      'Supplications for eating, sleeping & travel',
      'Dua memorization with correct pronunciation & meanings',
    ],
    syllabus: [
      'Daily morning & evening Adhkar (Athkar)',
      'Supplications for routine actions (eating, sleeping, travel, entering home)',
      'Dua memorization with correct pronunciation & Urdu/English meanings',
    ],
    info: {
      audience: 'Children, Beginners & Families',
      duration: '1 to 2 Months (Integrated with Nazra)',
      format: '1-on-1 Live Zoom session',
      prerequisites: 'None',
    },
  },
  {
    id: 'islamic',
    title: 'Islamic Studies',
    subtitle: 'Salah, Seerah & Akhlaq',
    desc: 'Age-appropriate Islamic learning: practical Salah (Namaz) guide, Pillars of Islam, Seerah of Prophet Muhammad ﷺ, and Akhlaq.',
    tag: 'Family & Children',
    arabic: 'الدراسات الإسلامية والآداب',
    badge: 'Faith & Morals',
    eyebrow: 'Pillars of Faith & Moral Character',
    icon: '☾',
    image: '/images/courses/islamic_studies_v2.jpg',
    action: 'Islamic Studies',
    points: [
      'Practical step-by-step Salah / Namaz guide',
      'Pillars of Islam & Articles of Faith (Iman)',
      'Seerah of Prophet ﷺ & Islamic manners (Akhlaq)',
    ],
    syllabus: [
      'Practical demonstration of Wudhu and 5 daily prayers (Salah)',
      'Five Pillars of Islam & Articles of Faith (Iman)',
      'Seerah (Life story) of Prophet Muhammad ﷺ',
      'Islamic manners, respect for parents, and social etiquette (Akhlaq & Adab)',
    ],
    info: {
      audience: 'Children, Teens & Reverts',
      duration: 'Ongoing Modular Course',
      format: '1-on-1 Live Zoom sessions',
      prerequisites: 'None',
    },
  },
];

export const SPECIAL_PROGRAMS: SpecialProgram[] = [
  {
    id: 'kids',
    title: 'Quran Classes for Kids Online',
    subtitle: 'Gentle, Patient & Child-Friendly Foundation',
    desc: 'Young minds learn best with patience and encouragement. We turn Quran lessons into an enjoyable daily habit with interactive screen sharing and positive motivation.',
    icon: '🧒',
    badge: 'Ages 4 – 14',
    highlight: 'Most Popular for Families',
    action: 'Enroll Your Child in Trial',
    points: [
      'Interactive Noorani Qaida reading with visual phonics',
      'Step-by-step practical Salah / Namaz training',
      'Memorization of short Surahs (Juz Amma) & daily Duas',
      'Weekly progress updates directly communicated with parents',
      'Gentle, patient teaching with zero harshness',
    ],
  },
  {
    id: 'ladies',
    title: 'Quran Classes for Ladies',
    subtitle: '100% Private, Respectful & Confidential',
    desc: 'Designed specifically for sisters, homemakers, university students, and working women seeking a flexible and comfortable online learning environment at home.',
    icon: '🧕',
    badge: 'Sisters & Daughters',
    highlight: 'Complete Privacy',
    action: 'Join Dedicated Ladies Track',
    points: [
      'Flexible class schedules around domestic & work commitments',
      'Tajweed perfection, Nazra fluency, & Quran translation',
      'Private 1-on-1 Zoom sessions with complete privacy',
      'Specialized Tajweed rules and Makharij correction',
      'Comfortable, non-judgmental, encouraging pace',
    ],
  },
  {
    id: 'personalized-mentorship',
    title: '1-on-1 Personalized Quran Mentorship',
    subtitle: 'Tailored Pacing for Rapid Progress',
    desc: 'Dedicated private sessions structured strictly around your individual learning speed, reading goals, and personalized feedback from Qari Sadiq Naeem.',
    icon: '🎓',
    badge: 'Individual Focus',
    highlight: '100% Dedicated Attention',
    action: 'Request 1-on-1 Mentorship',
    points: [
      'Full personal focus with zero classroom distractions',
      'Direct line of communication for questions & daily Sabaq',
      'Custom curriculum matching student’s exact learning speed',
      'Continuous Makharij evaluation and vocal Tarteel refinement',
      'Convenient schedule adjustment for busy schedules',
    ],
  },
  {
    id: 'adults',
    title: 'Online Quran Classes for Adults',
    subtitle: 'Tailored for Busy Professionals & Beginners',
    desc: 'It is never too late to learn the Quran. Whether starting from alphabet basics or polishing Tajweed, our adult track offers dignified, respectful, and flexible tutoring.',
    icon: '👨‍💼',
    badge: 'Ages 18 – 75+',
    highlight: 'Flexible Timing',
    action: 'Start as Adult Beginner',
    points: [
      'Early morning, late evening & weekend time slots',
      'Start from zero without hesitation, rush, or embarrassment',
      'Correction of common recitation errors in daily Salah',
      'Word-by-word Quran translation & spiritual reflection',
      'One-to-one confidentiality and customized progression',
    ],
  },
];
